In [15]:
import pandas as pd
import pandas_ta as ta
import numpy as np
import yfinance as yf

In [3]:
#data = pd.read_csv('data/cl-5m_bk.csv',sep=';',parse_dates=[[0,1]],index_col=0,dayfirst=True)
data = pd.read_csv('data/test.csv',sep=';',header=None,index_col=None)
        
cols=['Day','Time','Open','High','Low','Close','Volume']
data.columns = cols

In [5]:
data.head()

          Day   Time        Open        High         Low       Close  Volume
0  21/11/2008  00:00  184.754135  185.162883  184.679817  185.014247      75
1  21/11/2008  00:05  185.125724  185.274360  185.051406  185.088565      38
2  21/11/2008  00:10  185.162883  185.237201  185.051406  185.125724      27
3  21/11/2008  00:15  185.051406  185.868903  185.014247  185.868903     234
4  21/11/2008  00:20  185.868903  186.129015  185.645949  185.720267      74

In [7]:
data['Date'] = pd.to_datetime(data['Day'] + ' ' + data['Time'],
                                 format='%d/%m/%Y %H:%M')
data = data.set_index('Date')

In [9]:
#Drop the DT columns
data = data.drop(['Day','Time'],axis=1)

In [27]:

ticker = "aapl"
# Download data directly using yfinance
# Adjust period, start/end dates as needed
aapl_price = yf.download(ticker, period="5y")

if data is not None and not data.empty:

    aapl_price.columns = data.columns.get_level_values(0)
    print("Data downloaded successfully:")
    print(aapl_price.head())

    # Now, apply pandas_ta indicators to this DataFrame
    # Example: Add Simple Moving Average
    aapl_price.ta.sma(length=50, append=True)

    # Example: Add Relative Strength Index
    aapl_price.ta.rsi(append=True)

    # Example: Add MACD
    aapl_price.ta.macd(append=True)

    print("\nData with indicators:")
    print(aapl_price.head())
    # Assign the result back to df if needed
    df = aapl_price
else:
    print(f"Failed to download data for {ticker}")

[*********************100%***********************]  1 of 1 completed

Data downloaded successfully:
Price           Close       High        Low       Open     Volume
Date
2020-05-06  72.956589  73.589977  72.529471  72.915330  142333600
2020-05-07  73.711327  74.058363  73.281787  73.585136  115215200
2020-05-08  75.465775  75.519309  74.044694  74.373199  133838400
2020-05-11  76.653236  77.149636  74.762512  74.971785  145946400
2020-05-12  75.777252  77.792074  75.655584  77.339465  162301200

Data with indicators:
Price           Close       High        Low       Open     Volume  SMA_50  \
Date
2020-05-06  72.956589  73.589977  72.529471  72.915330  142333600     NaN
2020-05-07  73.711327  74.058363  73.281787  73.585136  115215200     NaN
2020-05-08  75.465775  75.519309  74.044694  74.373199  133838400     NaN
2020-05-11  76.653236  77.149636  74.762512  74.971785  145946400     NaN
2020-05-12  75.777252  77.792074  75.655584  77.339465  162301200     NaN

Price       RSI_14  MACD_12_26_9  MACDh_12_26_9  MACDs_12_26_9
Date
2020-05-06     NaN           NaN            NaN            NaN
2020-05-07     NaN           NaN            NaN            NaN
2020-05-08     NaN           NaN            NaN            NaN
2020-05-11     NaN           NaN            NaN            NaN
2020-05-12     NaN           NaN            NaN            NaN

In [29]:
aapl_price

Price,Close,High,Low,Open,Volume,SMA_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9
Date,,,,,,,,,,
2020-05-06,72.956589,73.589977,72.529471,72.915330,142333600,NaN,NaN,NaN,NaN,NaN
2020-05-07,73.711327,74.058363,73.281787,73.585136,115215200,NaN,NaN,NaN,NaN,NaN
2020-05-08,75.465775,75.519309,74.044694,74.373199,133838400,NaN,NaN,NaN,NaN,NaN
2020-05-11,76.653236,77.149636,74.762512,74.971785,145946400,NaN,NaN,NaN,NaN,NaN
2020-05-12,75.777252,77.792074,75.655584,77.339465,162301200,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2025-04-29,211.210007,212.240005,208.369995,208.690002,36827600,217.669601,53.270632,-2.115618,2.851096,-4.966715
2025-04-30,212.500000,213.580002,206.669998,209.300003,52286500,217.030201,54.201200,-1.332539,2.907341,-4.239879
2025-05-01,213.320007,214.559998,208.899994,209.080002,57365700,216.399201,54.817152,-0.638415,2.881171,-3.519587
2025-05-02,205.350006,206.990005,202.160004,206.089996,101010600,215.589601,48.052657,-0.723095,2.237193,-2.960288
2025-05-05,198.889999,204.100006,198.210007,203.100006,68915400,214.656401,43.379963,-1.296527,1.331009,-2.627536

In [25]:
data.ta.log_return(cumulative=True,append=True)

Date
2008-11-21 00:00:00    0.000000
2008-11-21 00:05:00    0.000402
2008-11-21 00:10:00    0.000602
2008-11-21 00:15:00    0.004609
2008-11-21 00:20:00    0.003809
                         ...
2008-11-21 07:55:00    0.015742
2008-11-21 08:00:00    0.014357
2008-11-21 08:05:00    0.009395
2008-11-21 08:10:00    0.001204
2008-11-21 08:15:00    0.002006
Name: CUMLOGRET_1, Length: 100, dtype: float64

In [27]:
data.ta.percent_return(cumulative=True,append=True)

Date
2008-11-21 00:00:00    0.000000
2008-11-21 00:05:00    0.000402
2008-11-21 00:10:00    0.000603
2008-11-21 00:15:00    0.004619
2008-11-21 00:20:00    0.003816
                         ...
2008-11-21 07:55:00    0.015867
2008-11-21 08:00:00    0.014461
2008-11-21 08:05:00    0.009440
2008-11-21 08:10:00    0.001205
2008-11-21 08:15:00    0.002008
Name: CUMPCTRET_1, Length: 100, dtype: float64

In [29]:
data.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'CUMLOGRET_1', 'CUMPCTRET_1'], dtype='object')

In [87]:
data

,Open,High,Low,Close,Volume,CUMLOGRET_1,CUMPCTRET_1
Date,,,,,,,
2008-11-21 00:00:00,184.754135,185.162883,184.679817,185.014247,75,0.000000,0.000000
2008-11-21 00:05:00,185.125724,185.274360,185.051406,185.088565,38,0.000402,0.000402
2008-11-21 00:10:00,185.162883,185.237201,185.051406,185.125724,27,0.000602,0.000603
2008-11-21 00:15:00,185.051406,185.868903,185.014247,185.868903,234,0.004609,0.004619
2008-11-21 00:20:00,185.868903,186.129015,185.645949,185.720267,74,0.003809,0.003816
...,...,...,...,...,...,...,...
2008-11-21 07:55:00,187.689689,188.544345,187.503895,187.949802,606,0.015742,0.015867
2008-11-21 08:00:00,187.986961,188.284232,187.057988,187.689689,1955,0.014357,0.014461
2008-11-21 08:05:00,187.689689,188.098438,186.723558,186.760717,1281,0.009395,0.009440
2008-11-21 08:10:00,186.797875,186.946511,184.679817,185.237201,2390,0.001204,0.001205
2008-11-21 08:15:00,185.237201,185.868903,185.051406,185.385837,1229,0.002006,0.002008

ModuleNotFoundError: No module named 'yfinance'